services:
  app:
    container_name: front-splitter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    tty: true
    volumes:
      - ./:/app
    networks:
      - splitter-network

volumes:
  front-splitter:

networks:
  splitter-network:
    external: true
