services:
  app:
    build:
      context: ./app/
      dockerfile: ./Dockerfile
    image: splitter/app:1.0
    container_name: splitter-app
    volumes:
      - ./app/src/:/app/
    tty: true
    ports:
      - 3001:3000
  db:
    build:
      context: ./db/
      dockerfile: ./Dockerfile
    image: splitter/db:1.0
    container_name: splitter-db
    volumes:
      - splitter-db:/var/lib/postgresql/data
      - ./db/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=splitter
  pgadmin4:
    image: dpage/pgadmin4:8.6
    container_name: splitter-pgadmin
    volumes:
      - splitter-pgadmin:/var/lib/pgadmin
    ports:
      - 8888:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@example.com
      - PGADMIN_DEFAULT_PASSWORD=passwd
    depends_on:
      - db
volumes:
  splitter-db:
  splitter-pgadmin: