openapi: "3.0.3"
info:
  title: Splitter API
  version: '1.0'
  description: |-
    This is a Splitter API
tags:
  - name: Groups
  - name: Users
  - name: Payments
paths:
  /groups:
    post:
      tags:
        - Groups
      description: |-
        Register group.
      responses:
        '200':
          description: OK
  /groups/{id}:
    get:
      tags:
        - Groups
      description: |-
        Get information of group.
      responses:
        '200':
          description: OK
    patch:
      tags:
        - Groups
      description: |-
        Change information of group.
      responses:
        '200':
          description: OK
  /users:
    post:
      tags:
        - Users
      description: |-
        Add an user.
      responses:
        '200':
          description: OK
  /users/{id}:
    get:
      tags:
        - Users
      description: |-
        Get information of an user.
      responses:
        '200':
          description: OK
    delete:
      tags:
        - Users
      description: |-
        Delete an user.
      responses:
        '200':
          description: OK
    patch:
      tags:
        - Users
      description: |-
        Update the information of an user.
      responses:
        '200':
          description: OK
  /payments:
    post:
      tags:
        - Payments
      description: |-
        Register the payment information.
      responses:
        '200':
          description: OK
  /payments/list:
    get:
      tags:
        - Payments
      description: |-
        Get the information of payments.
      responses:
        '200':
          description: OK
  /payments/{id}:
    get:
      tags:
        - Payments
      description: |-
        Get the information of payments.
      responses:
        '200':
          description: OK
    delete:
      tags:
        - Payments
      description: |-
        Delete the information of payments.
      responses:
        '200':
          description: OK
    patch:
      tags:
        - Payments
      description: |-
        Update the information of payments.
      responses:
        '200':
          description: OK
  /payments/done:
    post: 
      tags:
        - Payments
      description: |-
        Finish split money.
      responses:
        '200':
          description: OK
  /payments/doing:
    post: 
      tags:
        - Payments
      description: |-
        Unfinish split money.
      responses:
        '200':
          description: OK